/**
 * useGitHubExport (V2)
 * GitHubへのコードエクスポート機能を管理するカスタムフック
 * 多言語・プリセット対応
 */
import { useState, useCallback, useMemo } from 'react';
import { createRepository, addFileToRepo, updateFileInRepo } from '@/services/integrations/GitHubService';
import { getSubjectFinalProject, getSubjectFinalCode, getSubjectPresets, getSubjectProjectByPreset } from '@/utils/storage/codeStorage';
import { getPresetById } from '@/config/languageConfig';
import { isGitHubConnected, getGitHubUser, type GitHubUser } from '@/utils/storage/githubStorage';

interface ExportConfig {
  repoName: string;
  description: string;
  isPrivate: boolean;
  presetId?: string; // 追加: エクスポートするプリセット
}

interface ExportResult {
  url: string;
}

interface AvailablePreset {
  presetId: string;
  label: string;
  icon: string;
  updatedAt: string;
}

interface UseGitHubExportReturn {
  githubUser: GitHubUser | null;
  isConnected: boolean;
  hasCode: boolean;
  availablePresets: AvailablePreset[]; // 追加
  loading: boolean;
  error: string | null;
  success: ExportResult | null;
  exportToGitHub: (config: ExportConfig) => Promise<void>;
  resetState: () => void;
}

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

/**
 * プロジェクトに応じたREADMEを生成
 */
const generateReadme = (
  subjectTitle: string,
  presetId: string,
  fileNames: string[]
): string => {
  const preset = getPresetById(presetId);
  const presetLabel = preset?.label || 'Web基礎';
  const presetIcon = preset?.icon || '🌐';

  // ファイル構成
  const fileList = fileNames.map(name => `├── ${name}`).join('\n');

  // 使い方の説明（プリセットに応じて変更）
  let usageInstructions = '';
  switch (presetId) {
    case 'web-basics':
      usageInstructions = '`index.html` をブラウザで開いてください。';
      break;
    case 'typescript-basics':
      usageInstructions = `\`\`\`bash
npx ts-node main.ts
# または
npx tsc main.ts && node main.js
\`\`\``;
      break;
    case 'react':
      usageInstructions = `\`\`\`bash
npm create vite@latest my-app -- --template react-ts
# ファイルをコピーしてから
npm install
npm run dev
\`\`\``;
      break;
    case 'vue':
      usageInstructions = `\`\`\`bash
npm create vue@latest
# ファイルをコピーしてから
npm install
npm run dev
\`\`\``;
      break;
    case 'python':
      usageInstructions = `\`\`\`bash
python main.py
\`\`\``;
      break;
    default:
      usageInstructions = 'ファイルを実行環境に合わせてセットアップしてください。';
  }

  return `# ${subjectTitle}

${presetIcon} **${presetLabel}** プロジェクト

このプロジェクトは [Pathly](https://frontend-prod-xi.vercel.app) で学習した内容です。

## 📁 ファイル構成

\`\`\`
${fileList}
└── README.md
\`\`\`

## 🚀 使い方

${usageInstructions}

## 📅 作成日

${new Date().toLocaleDateString('ja-JP')}

---

*Generated by Pathly - プログラミング学習プラットフォーム*
`;
};

export const useGitHubExport = (
  subjectId: number,
  subjectTitle: string
): UseGitHubExportReturn => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<ExportResult | null>(null);

  const githubUser = getGitHubUser();
  const isConnected = isGitHubConnected();
  
  // 利用可能なプリセット一覧を取得
  const availablePresets = useMemo<AvailablePreset[]>(() => {
    const presets = getSubjectPresets(subjectId);
    return presets.map(p => {
      const presetDef = getPresetById(p.presetId);
      return {
        presetId: p.presetId,
        label: presetDef?.label || p.presetId,
        icon: presetDef?.icon || '📄',
        updatedAt: p.updatedAt,
      };
    }).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  }, [subjectId]);

  // 新しいプロジェクト形式を優先、なければ旧形式にフォールバック
  const finalProject = getSubjectFinalProject(subjectId);
  const finalCode = getSubjectFinalCode(subjectId);
  const hasCode = finalProject !== null || finalCode !== null || availablePresets.length > 0;

  const resetState = useCallback(() => {
    setLoading(false);
    setError(null);
    setSuccess(null);
  }, []);

  const exportToGitHub = useCallback(
    async (config: ExportConfig) => {
      if (!isConnected || !githubUser) {
        setError('GitHubと連携してください');
        return;
      }

      if (!hasCode) {
        setError('エクスポートするコードがありません。まずコードを書いてください。');
        return;
      }

      setLoading(true);
      setError(null);

      try {
        // リポジトリを作成
        const repo = await createRepository({
          name: config.repoName,
          description: config.description,
          isPrivate: config.isPrivate,
        });

        // GitHub APIのレート制限対策
        await delay(1500);

        // プリセットが指定された場合はそのプロジェクトを取得
        let projectToExport = config.presetId 
          ? getSubjectProjectByPreset(subjectId, config.presetId)
          : null;
        let presetId = config.presetId || 'web-basics';

        // プリセット指定がなければ最新プロジェクトを使用
        if (!projectToExport && finalProject) {
          projectToExport = { files: finalProject.files };
          presetId = finalProject.presetId;
        }

        // 新しいプロジェクト形式を使用
        if (projectToExport) {
          const fileNames = Object.keys(projectToExport.files);

          // READMEを更新
          const readmeContent = generateReadme(subjectTitle, presetId, fileNames);
          await updateFileInRepo(githubUser.login, config.repoName, {
            path: 'README.md',
            content: readmeContent,
          });

          // 各ファイルを追加
          for (const [filename, fileData] of Object.entries(projectToExport.files)) {
            if (fileData.content) {
              await addFileToRepo(githubUser.login, config.repoName, {
                path: filename,
                content: fileData.content,
              });
            }
          }
        } else if (finalCode) {
          // 旧形式にフォールバック
          const readmeContent = generateReadme(subjectTitle, 'web-basics', ['index.html', 'style.css', 'script.js']);
          await updateFileInRepo(githubUser.login, config.repoName, {
            path: 'README.md',
            content: readmeContent,
          });

          if (finalCode.html) {
            await addFileToRepo(githubUser.login, config.repoName, {
              path: 'index.html',
              content: finalCode.html,
            });
          }
          if (finalCode.css) {
            await addFileToRepo(githubUser.login, config.repoName, {
              path: 'style.css',
              content: finalCode.css,
            });
          }
          if (finalCode.js) {
            await addFileToRepo(githubUser.login, config.repoName, {
              path: 'script.js',
              content: finalCode.js,
            });
          }
        }

        setSuccess({ url: repo.html_url });
      } catch (err) {
        console.error('Export error:', err);
        setError(err instanceof Error ? err.message : 'エクスポートに失敗しました');
      } finally {
        setLoading(false);
      }
    },
    [isConnected, githubUser, finalProject, finalCode, hasCode, subjectTitle]
  );

  return {
    githubUser,
    isConnected,
    hasCode,
    availablePresets,
    loading,
    error,
    success,
    exportToGitHub,
    resetState,
  };
};

/**
 * リポジトリ名を日付ベースで生成
 */
export const generateRepoName = (): string => {
  const now = new Date();
  const date = now.toISOString().slice(0, 10).replace(/-/g, '');
  return `pathly-project-${date}`;
};