/**
 * useGitHubExport
 * GitHubへのコードエクスポート機能を管理するカスタムフック
 */
import { useState, useCallback } from 'react';
import { createRepository, addFileToRepo, updateFileInRepo } from '@/services/integrations/GitHubService';
import { getSubjectFinalCode } from '@/utils/storage/codeStorage';
import { isGitHubConnected, getGitHubUser, type GitHubUser } from '@/utils/storage/githubStorage';

interface ExportConfig {
  repoName: string;
  description: string;
  isPrivate: boolean;
}

interface ExportResult {
  url: string;
}

interface UseGitHubExportReturn {
  githubUser: GitHubUser | null;
  isConnected: boolean;
  hasCode: boolean;
  loading: boolean;
  error: string | null;
  success: ExportResult | null;
  exportToGitHub: (config: ExportConfig) => Promise<void>;
  resetState: () => void;
}

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const generateReadme = (subjectTitle: string): string => {
  return `# ${subjectTitle}

このプロジェクトは [Pathly](https://frontend-prod-xi.vercel.app) で学習した内容です。

## 📁 ファイル構成

\`\`\`
index.html  - HTML
style.css   - CSS
script.js   - JavaScript
\`\`\`

## 🚀 使い方

\`index.html\` をブラウザで開いてください。

## 📅 作成日

${new Date().toLocaleDateString('ja-JP')}

---

*Generated by Pathly - プログラミング学習プラットフォーム*
`;
};

export const useGitHubExport = (
  subjectId: number,
  subjectTitle: string
): UseGitHubExportReturn => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<ExportResult | null>(null);

  const githubUser = getGitHubUser();
  const isConnected = isGitHubConnected();
  const finalCode = getSubjectFinalCode(subjectId);
  const hasCode = finalCode !== null;

  const resetState = useCallback(() => {
    setLoading(false);
    setError(null);
    setSuccess(null);
  }, []);

  const exportToGitHub = useCallback(
    async (config: ExportConfig) => {
      if (!isConnected || !githubUser) {
        setError('GitHubと連携してください');
        return;
      }

      if (!finalCode) {
        setError('エクスポートするコードがありません。まずコードを書いてください。');
        return;
      }

      setLoading(true);
      setError(null);

      try {
        // リポジトリを作成
        const repo = await createRepository({
          name: config.repoName,
          description: config.description,
          isPrivate: config.isPrivate,
        });

        // GitHub APIのレート制限対策
        await delay(1500);

        // READMEを更新
        const readmeContent = generateReadme(subjectTitle);
        await updateFileInRepo(githubUser.login, config.repoName, {
          path: 'README.md',
          content: readmeContent,
        });

        // 各ファイルを追加
        if (finalCode.html) {
          await addFileToRepo(githubUser.login, config.repoName, {
            path: 'index.html',
            content: finalCode.html,
          });
        }
        if (finalCode.css) {
          await addFileToRepo(githubUser.login, config.repoName, {
            path: 'style.css',
            content: finalCode.css,
          });
        }
        if (finalCode.js) {
          await addFileToRepo(githubUser.login, config.repoName, {
            path: 'script.js',
            content: finalCode.js,
          });
        }

        setSuccess({ url: repo.html_url });
      } catch (err) {
        console.error('Export error:', err);
        setError(err instanceof Error ? err.message : 'エクスポートに失敗しました');
      } finally {
        setLoading(false);
      }
    },
    [isConnected, githubUser, finalCode, subjectTitle]
  );

  return {
    githubUser,
    isConnected,
    hasCode,
    loading,
    error,
    success,
    exportToGitHub,
    resetState,
  };
};

/**
 * リポジトリ名を日付ベースで生成
 */
export const generateRepoName = (): string => {
  const now = new Date();
  const date = now.toISOString().slice(0, 10).replace(/-/g, '');
  return `pathly-project-${date}`;
};