/**
 * GitHub Export Modal
 * 学習コードをGitHubリポジトリにエクスポートするモーダル
 */
import React, { useState } from 'react';
import { createRepository, addFileToRepo, updateFileInRepo } from '@/services/integrations/GitHubService';
import { getSubjectFinalCode } from '@/utils/storage/codeStorage';
import { isGitHubConnected, getGitHubUser } from '@/utils/storage/githubStorage';

interface GitHubExportModalProps {
  subjectId: number;
  subjectTitle: string;
  onClose: () => void;
}

const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const generateRepoName = () => {
  const now = new Date();
  const date = now.toISOString().slice(0, 10).replace(/-/g, '');
  return `pathly-project-${date}`;
};

export const GitHubExportModal: React.FC<GitHubExportModalProps> = ({
  subjectId,
  subjectTitle,
  onClose,
}) => {
  const [repoName, setRepoName] = useState(generateRepoName());
  const [description, setDescription] = useState(`Pathlyで学習: ${subjectTitle}`);
  const [isPrivate, setIsPrivate] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<{ url: string } | null>(null);

  const githubUser = getGitHubUser();
  const finalCode = getSubjectFinalCode(subjectId);
  const hasCode = finalCode !== null;

  const handleExport = async () => {
    if (!isGitHubConnected() || !githubUser) {
      setError('GitHubと連携してください');
      return;
    }

    if (!finalCode) {
      setError('エクスポートするコードがありません。まずコードを書いてください。');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const repo = await createRepository({
        name: repoName,
        description,
        isPrivate,
      });

      await delay(1500);

      const readmeContent = generateReadme(subjectTitle);
      await updateFileInRepo(githubUser.login, repoName, {
        path: 'README.md',
        content: readmeContent,
      });

      if (finalCode.html) {
        await addFileToRepo(githubUser.login, repoName, {
          path: 'index.html',
          content: finalCode.html,
        });
      }
      if (finalCode.css) {
        await addFileToRepo(githubUser.login, repoName, {
          path: 'style.css',
          content: finalCode.css,
        });
      }
      if (finalCode.js) {
        await addFileToRepo(githubUser.login, repoName, {
          path: 'script.js',
          content: finalCode.js,
        });
      }

      setSuccess({ url: repo.html_url });
    } catch (err) {
      console.error('Export error:', err);
      setError(err instanceof Error ? err.message : 'エクスポートに失敗しました');
    } finally {
      setLoading(false);
    }
  };

  const generateReadme = (title: string) => {
    return `# ${title}

このプロジェクトは [Pathly](https://frontend-prod-xi.vercel.app) で学習した内容です。

## 📁 ファイル構成

\`\`\`
index.html  - HTML
style.css   - CSS
script.js   - JavaScript
\`\`\`

## 🚀 使い方

\`index.html\` をブラウザで開いてください。

## 📅 作成日

${new Date().toLocaleDateString('ja-JP')}

---

*Generated by Pathly - プログラミング学習プラットフォーム*
`;
  };

  if (success) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content github-export-modal" onClick={(e) => e.stopPropagation()}>
          <div className="export-success">
            <span className="success-icon">🎉</span>
            <h3>エクスポート完了！</h3>
            <p>GitHubリポジトリが作成されました</p>
            <a
              href={success.url}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-view-repo"
            >
              🐙 リポジトリを見る
            </a>
            <button className="btn-secondary" onClick={onClose}>
              閉じる
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content github-export-modal" onClick={(e) => e.stopPropagation()}>
        <h3>🐙 GitHubにエクスポート</h3>
        
        {!isGitHubConnected() ? (
          <div className="export-warning">
            <p>GitHubと連携してからエクスポートしてください</p>
            <a href="/profile" className="btn-primary">
              プロフィールで連携する
            </a>
          </div>
        ) : (
          <>
            <div className="export-info">
              <p>
                {hasCode ? '最終セクションのコードをエクスポートします' : 'コードがありません'}
              </p>
              <p className="export-user">
                エクスポート先: <strong>@{githubUser?.login}</strong>
              </p>
            </div>

            <div className="form-group">
              <label>リポジトリ名</label>
              <input
                type="text"
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                placeholder="my-project"
              />
              <small className="input-hint">※ 英数字とハイフンのみ使用可能</small>
            </div>

            <div className="form-group">
              <label>説明</label>
              <input
                type="text"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="プロジェクトの説明"
              />
            </div>

            <div className="form-group checkbox-group">
              <label>
                <input
                  type="checkbox"
                  checked={isPrivate}
                  onChange={(e) => setIsPrivate(e.target.checked)}
                />
                プライベートリポジトリにする
              </label>
            </div>

            {error && <div className="error-message">{error}</div>}

            <div className="modal-actions">
              <button className="btn-secondary" onClick={onClose} disabled={loading}>
                キャンセル
              </button>
              <button
                className="btn-github-export"
                onClick={handleExport}
                disabled={loading || !hasCode}
              >
                {loading ? 'エクスポート中...' : 'エクスポート'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};
