/**
 * GitHub Export Modal
 * 学習コードをGitHubリポジトリにエクスポートするモーダル
 */
import React, { useState } from 'react';
import { createRepository, addFileToRepo } from '@/services/GitHubService';
import { getSubjectCodes } from '@/utils/codeStorage';
import { isGitHubConnected, getGitHubUser } from '@/utils/githubStorage';

interface GitHubExportModalProps {
  subjectId: number;
  subjectTitle: string;
  onClose: () => void;
}

export const GitHubExportModal: React.FC<GitHubExportModalProps> = ({
  subjectId,
  subjectTitle,
  onClose,
}) => {
  const [repoName, setRepoName] = useState(
    `pathly-${subjectTitle.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 30)}`
  );
  const [description, setDescription] = useState(`Pathlyで学習: ${subjectTitle}`);
  const [isPrivate, setIsPrivate] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<{ url: string } | null>(null);

  const githubUser = getGitHubUser();
  const codes = getSubjectCodes(subjectId);

  const handleExport = async () => {
    if (!isGitHubConnected()) {
      setError('GitHubと連携してください');
      return;
    }

    if (codes.length === 0) {
      setError('エクスポートするコードがありません');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // リポジトリ作成
      const repo = await createRepository({
        name: repoName,
        description,
        isPrivate,
      });

      // README.mdを作成
      const readmeContent = generateReadme(subjectTitle, codes);
      await addFileToRepo(githubUser!.login, repoName, {
        path: 'README.md',
        content: readmeContent,
      });

      // 各セクションのコードをファイルとして追加
      for (const codeData of codes) {
        const ext = getFileExtension(codeData.language);
        const fileName = `section-${codeData.sectionId}.${ext}`;
        await addFileToRepo(githubUser!.login, repoName, {
          path: `src/${fileName}`,
          content: codeData.code,
        });
      }

      setSuccess({ url: repo.html_url });
    } catch (err) {
      setError(err instanceof Error ? err.message : 'エクスポートに失敗しました');
    } finally {
      setLoading(false);
    }
  };

  const generateReadme = (title: string, codes: { sectionId: number; language: string }[]) => {
    return `# ${title}

このプロジェクトは [Pathly](https://frontend-prod-xi.vercel.app) で学習した内容です。

## 📚 学習内容

${codes.map((c) => `- セクション ${c.sectionId} (${c.language})`).join('\n')}

## 🚀 作成日

${new Date().toLocaleDateString('ja-JP')}

---

*Generated by Pathly - プログラミング学習プラットフォーム*
`;
  };

  const getFileExtension = (language: string): string => {
    const extensions: Record<string, string> = {
      javascript: 'js',
      typescript: 'ts',
      python: 'py',
      html: 'html',
      css: 'css',
      java: 'java',
      go: 'go',
      rust: 'rs',
      ruby: 'rb',
      php: 'php',
    };
    return extensions[language] || 'txt';
  };

  if (success) {
    return (
      <div className="modal-overlay" onClick={onClose}>
        <div className="modal-content github-export-modal" onClick={(e) => e.stopPropagation()}>
          <div className="export-success">
            <span className="success-icon">🎉</span>
            <h3>エクスポート完了！</h3>
            <p>GitHubリポジトリが作成されました</p>
            <a
              href={success.url}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-view-repo"
            >
              🐙 リポジトリを見る
            </a>
            <button className="btn-secondary" onClick={onClose}>
              閉じる
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content github-export-modal" onClick={(e) => e.stopPropagation()}>
        <h3>🐙 GitHubにエクスポート</h3>
        
        {!isGitHubConnected() ? (
          <div className="export-warning">
            <p>GitHubと連携してからエクスポートしてください</p>
            <a href="/profile" className="btn-primary">
              プロフィールで連携する
            </a>
          </div>
        ) : (
          <>
            <div className="export-info">
              <p>
                <strong>{codes.length}</strong> セクションのコードをエクスポートします
              </p>
              <p className="export-user">
                エクスポート先: <strong>@{githubUser?.login}</strong>
              </p>
            </div>

            <div className="form-group">
              <label>リポジトリ名</label>
              <input
                type="text"
                value={repoName}
                onChange={(e) => setRepoName(e.target.value)}
                placeholder="my-project"
              />
            </div>

            <div className="form-group">
              <label>説明</label>
              <input
                type="text"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="プロジェクトの説明"
              />
            </div>

            <div className="form-group checkbox-group">
              <label>
                <input
                  type="checkbox"
                  checked={isPrivate}
                  onChange={(e) => setIsPrivate(e.target.checked)}
                />
                プライベートリポジトリにする
              </label>
            </div>

            {error && <div className="error-message">{error}</div>}

            <div className="modal-actions">
              <button className="btn-secondary" onClick={onClose} disabled={loading}>
                キャンセル
              </button>
              <button
                className="btn-github-export"
                onClick={handleExport}
                disabled={loading || codes.length === 0}
              >
                {loading ? 'エクスポート中...' : 'エクスポート'}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
};
